version: "3.8"

networks:
  &app-network aviator_network:
    driver: bridge
    external: true

x-common-template: &common-template
  restart: always
  volumes:
    - /etc/localtime:/etc/localtime:ro
  networks:
    - *app-network

services:

  &frontend-service frontend:
    <<: *common-template
    hostname: *frontend-service
    build:
      context: .
      dockerfile: .docker/frontend/dev/Dockerfile
    user: "1000:1000"
    ports:
      - "8800:${PORT}"
    volumes:
      - .:/app
