---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: {{ .Release.Name }}-http
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Release.Name }}
