env: production

image:
  repository: localhost:5000/frontend
  pullPolicy: IfNotPresent
  tag: master

replica:
  count: 2

containers:
  restartPolicy: Always

ports:
  containerPort: 80
  servicePort: 8800

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "300m"
    memory: "400Mi"
